### ISSUE TITLE
Download filtered csv file

### ISSUE THREAD

**Issue by kruegert** [labsyspharm/cycif_viewer#10]
Button to download the filtered csv file. CSV values should be 1 if within range and 0 if outside of range.

**Comment by jessupjs** [comment]
Currently implemented to:
+ Export gated channel ranges
+ Export gated encodings (currently for selected channel - need to ck if all channels should be included)

**Comment by kruegert** [comment]
filename should be based on dataset name.

**Comment by kruegert** [comment]
server now return csv filenames based on user input
