### ISSUE TITLE
rename the selection 'Channel file path' as 'Image file path' in the data upload page

### ISSUE THREAD

**Issue by tuuliavallius** [labsyspharm/cycif_viewer#20]

**Comment by jessupjs** [comment]
Nice thought @tuuliavallius  - the new wording has been implemented and will soon available in a `gating` branch update (and soon after in `master`):

<img width="788" alt="Screen Shot 2020-11-23 at 3 27 34 PM" src="https://user-images.githubusercontent.com/36556988/100012174-d6ff3980-2da0-11eb-9fef-f41a4278eda4.png">

**Comment by kruegert** [comment]
done
