### ISSUE TITLE
div height

### ISSUE THREAD

**Issue by kruegert** [labsyspharm/cycif_viewer#29]
Unnecessary space (height) causes scrollbars.

![image](https://user-images.githubusercontent.com/31503434/106758907-14354280-6600-11eb-8e4e-9debe6fba09b.png)

**Comment by jessupjs** [comment]
This was a quick-and-dirty workaround to access the color picker - now fixed as slider padding with some other styling updates. More troubling is the way the scroll bars render in Windows Chrome. After a pull could you update on the scroll bar appearance before I open a new issue? @kruegert
