### ISSUE TITLE
plateau lens bug

### ISSUE THREAD

**Issue by kruegert** [labsyspharm/cycif_viewer#30]
Left and right side of plateau lens seem to be switched

![image](https://user-images.githubusercontent.com/31503434/106759184-73935280-6600-11eb-8148-21d05c299aaf.png)

**Comment by jessupjs** [comment]
I see the issue, but am not able to reproduce it locally. @kruegert - were there some antecedent exploration activities before this appeared? Can also connect offline.

**Comment by kruegert** [comment]
seems less important for now. I'll close it.
