### ISSUE TITLE
h&e filter causes problems for following filters

### ISSUE THREAD

**Issue by kruegert** [labsyspharm/cycif_viewer#31]
With 163 dataset, when switching over the filters, as soon as the H&E filter is loaded the H&e filter panel styays and does not update to other filters:

![image](https://user-images.githubusercontent.com/31503434/106759642-0207d400-6601-11eb-845b-964ad6d86c49.png)

**Comment by jessupjs** [comment]
I am unable to reproduce this locally, and do not believe this particular filter utilizes async functions that would cause a destruction failure (a previously observed bug for similar box displays). @kruegert - if time allows, we can perhaps check your setup to see if there might be a setup issue that I have not addressed.

**Comment by kruegert** [comment]
Try it with a dataset that does not have these channels/names.

**Comment by jessupjs** [comment]
Ah - that's it. Thank you. The issue is that the filter does not handle and skip datasets without H&E channels.

**Comment by kruegert** [comment]
Fixed.
