### ISSUE TITLE
Segementation Filter not working

### ISSUE THREAD

**Issue by kruegert** [labsyspharm/cycif_viewer#34]
The mask does not load. It loads when the user adds a new channel. So probaly it just needs a refresh after activation or something.
![image](https://user-images.githubusercontent.com/31503434/106760633-0680bc80-6602-11eb-9d69-0746e32cca26.png)

**Comment by jessupjs** [comment]
The behind-the-scenes server call is working, but the current caching strategy from `master` is no longer compatible with viewer management logic. Will connect w @simonwarchol for update.

**Comment by kruegert** [comment]
ok would be great to fix. Seem to not always load on Sardana dataset.
