### ISSUE TITLE
Lens turns blue when channel is deactivated

### ISSUE THREAD

**Issue by kruegert** [labsyspharm/cycif_viewer#37]
lens turns blue (unprocessed tiles) whenever a channel is deactivated and then stays like this no matter what is done.

![image](https://user-images.githubusercontent.com/31503434/106761480-dbe33380-6602-11eb-93c9-e8717b6a99cc.png)

**Comment by jessupjs** [comment]
Perhaps also a caching issue. Although similar outcomes have occurred when the viewer is either waiting for new tiles to be loaded or is overwhelmed by voluminous tile requests and simply reverts to the blue/green view. Will investigate.

**Comment by jessupjs** [comment]
Simplest fix - inc. tile cache max (from 50 to 100).
