### ISSUE TITLE
Store and Load Annotations

### ISSUE THREAD

**Issue by kruegert** [labsyspharm/cycif_viewer#47]
- button and functionality to store current annotations to the database (for a current dataset)
- button and functionality to load annotations from database (for current dataset).

For now, buttons can go to the top menu of the application (create new field: Annotation with Store and Load)

**Comment by kruegert** [comment]
**First step:** 
The schema can be:
id, annotation_group, name, description, shapetype, shape, 
120, "immune", "Sardana96", "This is a cancer region", "circle", "cx='20',cy='44',r='20'"
(Shapes could also be polygons and rectangles)

load/save from db should work with the dotter panel. 

**Second Step**
Then after that extend to something along those lines:

id, annotation_group, name, description, shapetype, shape, cell ids (optional), active_channels[], channel_color_schemes[], channel_intensities[], ....
120, "immune", "Sardana96", "This is a cancer region", "circle", "cx='20',cy='44',r='20'", "2,44,66,768,546,77,66", ["Hoechst1, ...], [[,255,255,255], ...], [0.5,...], ....

**Comment by jessupjs** [comment]
This is running but needs bug fixing.

**Comment by jessupjs** [comment]
Closing to force new DB bugs to be added in new issues.
