### ISSUE TITLE
Visualize cells (in or out) by filtered ranges

### ISSUE THREAD

**Issue by kruegert** [labsyspharm/cycif_viewer#9]
Use cel-based rendering to display which cells are still within the set ranges. Allow to toggle of cell-based nredering to still see underlying intensity values.

**Comment by jessupjs** [comment]
Currently the gating control panel on left can adjust range one-channel-at-a-time. Outlines within the viewer will appear for all cells within that range (you may need to click on the image to see them).

<img width="600" alt="Screen Shot 2020-10-05 at 8 12 36 PM" src="https://user-images.githubusercontent.com/36556988/95144647-292fc100-0747-11eb-8980-67ea3589edc6.png">

Several interactions are needed (should base on user feedback):
+ Panel list indicators that gating has / has not occurred.
+ Color options for outline/fill
+ Multi-channel editing (if desired)

**Comment by kruegert** [comment]
Works well. Merged into gating.
